schema_version = "1.0.0"
id = "jnt_sandbox"
version = "0.1.0"
type = "add-on"
name = "JNT Sandbox"
tagline = "A collection of experiments and custom nodes"
maintainer = "Jerv Norsk <jerv.norsk@gmail.com>"
website = "https://extensions.blender.org/add-ons/jnt_sandbox/"
tags = [ "Geometry Nodes",]
blender_version_min = "4.3.2"
license = [ "SPDX:GPL-3.0-or-later",]
copyright = [ "2025 JervNorsk",]

[build]
paths_exclude_pattern = [ "__pycache__/", "/.git/", "/build/",]
