[settings]
#trace = true

[tools]
#act = "latest"
#gh = "latest"

#[task_config]
#includes = [
#    "tasks.toml",
#    "modules/core/tasks.toml",
#    "modules/extensions/tasks.toml",
#]

[tasks."mise:tools"]
dir = '{{cwd}}/.mise/tools'
run = 'mise r mise:tools:{{arg(var=true, default="tasks")}}'

[tasks."mise:registry"]
dir = "{{cwd}}/.mise/registry"
run = "mise r mise:registry:{{arg(var=true, default='tasks')}}"

[tasks."blender:core"]
dir = "{{cwd}}/modules/core"
run = "mise r blender:core:{{arg(var=true, default='tasks')}}"

[tasks."blender:extensions"]
dir = "{{cwd}}/modules/extensions"
run = "mise r blender:extensions:{{arg(var=true, default='tasks')}}"

#[tasks."github:actions:pull"]
#description = "Pull changes of GitHub Actions"
#run = [
#    "git subtree pull --prefix=.github/actions/setup origin actions/setup --squash"
#]
#
#[tasks."github:actions:push"]
#description = "Push changes of GitHub Actions"
#run = [
#    "git subtree push --prefix=.github/actions/setup origin actions/setup"
#]
#
#[tasks."mise:tools:pull"]
#description = "Pull changes of Mise tools"
#run = [
#    "git subtree pull --prefix=.mise/tools/blender/aqua origin mise/blender/aqua --squash",
#    "git subtree pull --prefix=.mise/tools/blender/plugin origin mise/blender/plugin --squash",
#]
#
#[tasks."mise:tools:push"]
#description = "Push changes of Mise tools"
#run = [
#    "git subtree push --prefix=.mise/tools/blender/aqua origin mise/blender/aqua",
#    "git subtree push --prefix=.mise/tools/blender/plugin origin mise/blender/plugin",
#]
#
##[tasks."mise:tools:install"]
##description = "Install Mise tools"
##run = [
##    "mise plugins update blender",
##    "mise -v install blender"
##]
#
##[tasks."blender:core"]
##run = [
##    "mise -C modules/core r blender:core:"
##]
