[tools]
gh = "latest"
python = "3.11"
uv = "0.5.24"

[env]
MISE_PYTHON_UV_VENV_AUTO = true
_.python.venv = { path = ".venv", create = true }

[tasks.gh-actions-pull]
description = "Pull changes of GitHub Actions"
run = [
    "git subtree pull --prefix=.github/actions/setup origin actions/setup --squash"
]

[tasks.gh-actions-push]
description = "Push changes of GitHub Actions"
run = [
    "git subtree push --prefix=.github/actions/setup origin actions/setup"
]

[tasks.extensions-build]
description = "Build the project"
run = [
    "mkdir build || exit 0",
    "cd build && mkdir extensions || exit 0",
    "blender -c extension build --source-dir modules/extensions/sandbox --output-dir build/extensions",
    "blender -c extension build --source-dir modules/extensions/comfyui --output-dir build/extensions",
    "blender -c extension server-generate --repo-dir build/extensions"
]

[tasks.extensions-version]
description = "Set a new version to Blender extension/s"
run = [
    'python ./.mise/scripts/set_extension_version.py {{arg(name="extension_name")}} {{arg(name="version")}}'
]

[tasks.extensions-publish]
description = "Publish Blender Extesion on release branch with GitHub Actions"
run = [
    "gh workflow run jnt-blender-extensions.yml --ref develop"
]

[tasks.extensions-publish-status]
description = ""
run = [
    "gh run list --workflow=jnt-blender-extensions.yml"
]

[tasks.extensions-unpublish]
description = "Drop Blender extensions on release/next"
run = [
    "git push -d origin release/next"
]

[tasks.extensions]
description = "Access to Blender extensions CLI"
run = [
    "blender -c extension"
]

[tasks.extensions-install]
description = "Install extension to Blender"
run = [
    "blender -c extension repo-add jnt --name JNT --url https://raw.githubusercontent.com/JervNorsk/jnt-blender/refs/heads/release/index.json"
]

[tasks.extensions-uninstall]
description = "Uninstall extension to Blender"
run = [
    "blender -c extension repo-remove jnt"
]

[tasks.check]
description = ""
run = [
    "blender -c extension sync"
]
