[tools]
gh = "latest"
python = "3.11"
uv = "0.5.24"

[env]
MISE_PYTHON_UV_VENV_AUTO = true
_.python.venv = { path = ".venv", create = true }

[tasks.extensions-build]
description = "Build the project"
run = [
    "mkdir build || exit 0",
    "cd build && mkdir extensions || exit 0",
    "blender -c extension build --source-dir modules/extensions/sandbox --output-dir build/extensions",
    "blender -c extension build --source-dir modules/extensions/comfyui --output-dir build/extensions",
    "blender -c extension server-generate --repo-dir build/extensions"
]

[tasks.extensions-ci]
description = "Run continuous integration"
run = [
    "gh workflow run ci.yml --ref develop"
]

[tasks.extensions]
description = "Access to Blender Extensions CLI"
run = [
    "blender -c extension"
]
