name: "JNT Blender Setup"
description: "Extensive Blender installation management"
author: "JervNorsk"

inputs:
  version:
    description: "The Blender version to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Blender Installation
      uses: actions/cache@v4
      with:
        path: /opt/hostedtoolcache/blender/${{ inputs.version }}
        key: ${{ runner.os }}-blender-${{ hashFiles('**/action.yml') }}-${{ inputs.version }}
        restore-keys: |
          ${{ runner.os }}-blender-

    - name: Install Blender
      uses: moguri/setup-blender@v1
      with:
        blender-version: ${{ inputs.version }}
