[project]
name = "jnt"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jnt-sandbox",
    "jnt-comfyui",
]

[tool.uv.workspace]
members = ["modules/*"]

[tool.uv.sources]
jnt-sandbox = { workspace = true }
jnt-comfyui = { workspace = true }