name: 'JNT Blender Extensions'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout to workflow branch
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Mise
        uses: jdx/mise-action@v2
        with:
          cache: true

      # TODO: install Blender via MISE

      - name: Install Blender
        uses: JervNorsk/jnt-blender@actions/setup
        with:
          version: 4.3.0

      - name: Install zip and unzip
        run: sudo apt-get update && sudo apt-get install -y zip unzip

      - name: Run build
        run: mise run extensions-build

      - if: github.ref == 'refs/heads/release'
        name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jnt-blender-extensions
          path: ./build/extensions

  deploy:
    if: github.ref == 'refs/heads/release'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout to workflow branch
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if branch exists
        id: check_branch
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/release; then
            echo "branch_exists=true" >> $GITHUB_ENV
          else
            echo "branch_exists=false" >> $GITHUB_ENV
          fi

      - name: Create new branch if not exists
        if: ${{ env.branch_exists == 'false' }}
        run: |
          git checkout --orphan release
          if [ -f .gitmodules ]; then
            git rm --cached .gitmodules
            rm .gitmodules
          fi
          git rm -rf .
          echo "# New Branch" > README.md
          git add README.md
          git commit -m "Initial commit on new empty branch"
          git push origin release

      - name: Pull latest changes if branch exists
        if: ${{ env.branch_exists == 'true' }}
        run: |
          git checkout release
          git pull origin release

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: jnt-blender-extensions
          path: ./

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update release content"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push -u origin release